version: '3.7'

services:
  practice-db:
    image: mysql:5.7
    container_name: practice-db
    ports:
      - 3306:3306
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
    environment:
      - "TZ=${TZ:-Asia/Tokyo}"
      - "MYSQL_ROOT_PASSWORD=test"
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
